// Generate CONTENT-INTENT-REGISTRY.md — the canonical ledger of every published
// FAQ URL and its search intent. Use this before authoring a new FAQ to avoid
// publishing duplicate-intent content (also enforced by faq:validate).
//
// Run: pnpm --filter @workspace/api-server run faq:registry

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildDatasetFromSeed, faqSeed } from "@workspace/faq";

const dataset = buildDatasetFromSeed(faqSeed);

const lines: string[] = [];
lines.push("# Content Intent Registry");
lines.push("");
lines.push(
  "> Auto-generated by `pnpm --filter @workspace/api-server run faq:registry`. Do not edit by hand.",
);
lines.push(
  "> The single source of truth is `lib/faq/src/seed.ts`.",
);
lines.push("");
lines.push(
  "Every published FAQ URL and the search intent it owns. Before adding a new FAQ, check this ledger (and `faq:validate`) so two pages never target the same intent.",
);
lines.push("");

lines.push("## Hubs");
lines.push("");
lines.push("| URL | Intent |");
lines.push("| --- | --- |");
lines.push("| `/faq` | FAQ hub — all questions grouped by category |");
for (const t of dataset.topics()) {
  lines.push(`| \`/faq/topics/${t.slug}\` | Topic cluster: ${t.title} |`);
}
lines.push("");

lines.push("## Questions");
lines.push("");
lines.push("| URL | Category | Intent (question) |");
lines.push("| --- | --- | --- |");
for (const item of dataset.all()) {
  const q = item.question.replace(/\|/g, "\\|");
  lines.push(`| \`/faq/${item.slug}\` | ${item.categoryTitle} | ${q} |`);
}
lines.push("");

const here = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.resolve(here, "../../../../CONTENT-INTENT-REGISTRY.md");
writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`Wrote intent registry (${dataset.all().length} questions) to ${outPath}`);
