// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/font-pairings/A_CormorantGaramond.tsx": () => import("../components/mockups/font-pairings/A_CormorantGaramond.tsx"),
  "./components/mockups/font-pairings/B_PlayfairDisplay.tsx": () => import("../components/mockups/font-pairings/B_PlayfairDisplay.tsx"),
  "./components/mockups/font-pairings/C_BodoniModa.tsx": () => import("../components/mockups/font-pairings/C_BodoniModa.tsx"),
  "./components/mockups/font-pairings/D_Lora.tsx": () => import("../components/mockups/font-pairings/D_Lora.tsx"),
  "./components/mockups/lot-ctas/Current.tsx": () => import("../components/mockups/lot-ctas/Current.tsx"),
  "./components/mockups/lot-ctas/DarkCards.tsx": () => import("../components/mockups/lot-ctas/DarkCards.tsx"),
  "./components/mockups/lot-ctas/EditorialLinks.tsx": () => import("../components/mockups/lot-ctas/EditorialLinks.tsx"),
  "./components/mockups/process-section/ConnectedTimeline.tsx": () => import("../components/mockups/process-section/ConnectedTimeline.tsx"),
  "./components/mockups/process-section/Current.tsx": () => import("../components/mockups/process-section/Current.tsx"),
  "./components/mockups/process-section/FeaturedBento.tsx": () => import("../components/mockups/process-section/FeaturedBento.tsx"),
  "./components/mockups/process-section/StackedMilestones.tsx": () => import("../components/mockups/process-section/StackedMilestones.tsx"),
  "./components/mockups/why-choose/VariantA.tsx": () => import("../components/mockups/why-choose/VariantA.tsx"),
  "./components/mockups/why-choose/VariantB.tsx": () => import("../components/mockups/why-choose/VariantB.tsx"),
  "./components/mockups/why-choose/VariantC.tsx": () => import("../components/mockups/why-choose/VariantC.tsx")
};
