// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/font-pairings/A_CormorantGaramond.tsx": () => import("../components/mockups/font-pairings/A_CormorantGaramond.tsx"),
  "./components/mockups/font-pairings/B_PlayfairDisplay.tsx": () => import("../components/mockups/font-pairings/B_PlayfairDisplay.tsx"),
  "./components/mockups/font-pairings/C_BodoniModa.tsx": () => import("../components/mockups/font-pairings/C_BodoniModa.tsx"),
  "./components/mockups/font-pairings/D_Lora.tsx": () => import("../components/mockups/font-pairings/D_Lora.tsx")
};
